packages:
  - "packages/eslint-config"
  - "packages/eslint-config-custom-server"
  - "packages/jest-presets"
  - "packages/prettier-config"
  - "packages/prettier-config"
  - "packages/tsconfig"
  - "packages/vite-vitest-config"
